apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}